### ISSUE TITLE
Idea: generate JUnit-style XML from the results

### ISSUE THREAD

**Issue by gergelypolonkai** [yunojuno/django-juno-testrunner#14]
I know of some projects that run their tests via Jenkins, which can process JUnit style XML files and show the results. It would be nice if (even if optionally) the Juno test runner could generate such XML files. There is [django-jux](https://github.com/Motiejus/django-jux) for this, but having two test runners configured for one project seems to be an overkill, and that one is unmaintained for a while.

**Comment by hugorodgerbrown** [comment]
Hopefully this is fixed by #15 - thank you @gergelypolonkai
