### ISSUE TITLE
Django 1.9 deprecation warning

### ISSUE THREAD

**Issue by stevejalim** [yunojuno/django-juno-testrunner#8]
`RemovedInDjango19Warning: django.utils.unittest will be removed in Django 1.9.` - worth us getting ahead of the curve and moving away from the bundled `unittest`

**Comment by stevejalim** [comment]
...while also keeping 1.6 compatibility

**Comment by gergelypolonkai** [comment]
From [`junorunner/extended_runner.py`](https://github.com/yunojuno/django-juno-testrunner/blob/master/junorunner/extended_runner.py#L16):

    try:¬
        # Django 1.6¬
        from django.utils.unittest import result¬
    except ImportError:¬
        # Django 1.7+ because bundled unittest is going away¬
        from unittest import result¬

I guess it could be closed…

**Comment by hugorodgerbrown** [comment]
@Geekfish does #21 supercede this?

**Comment by Geekfish** [comment]
no, but looking at the code that was mentioned above I think we're safe. Tests pass fine in 1.9 and 1.10 on the PR.

**Comment by Geekfish** [comment]
This looks fine, warning may show up before 1.9 but things won't break. Closing.
